/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import data.CRUD_MySQL;
import konektor.Kendaraan;
import data.CRUD_SQLite;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import java.util.*;
import java.sql.*;
import konektor.Pembeli;

/**
 *
 * @author Aditya Nugraha
 */
public class FormPembeli extends javax.swing.JFrame {

    private final CRUD_MySQL crud = new CRUD_MySQL();
    private final DefaultTableModel model = new DefaultTableModel();
    private Pembeli p;
    private String status;

    /**
     * Creates new form FormPembeli
     */
    public FormPembeli() {
        initComponents();
        this.kolomTabel();
        this.getData();
    }

    private void kolomTabel() {
        model.addColumn("ID");
        model.addColumn("Nomor Identitas");
        model.addColumn("Nama");
        model.addColumn("Tanggal Pembelian");
        model.addColumn("ID Barang");
        model.addColumn("Jumlah");
        model.addColumn("Total Harga");
        model.addColumn("DP");
        model.addColumn("Status");
        model.addColumn("Bonus");
        tbPembeli.setModel(model);
    }

    public void getData() {
        try {
            model.setRowCount(0);
            crud.bukaKoneksi();
            ArrayList<Pembeli> list = crud.read();
            System.out.println(list.size());
            for (Pembeli p : list) {
                model.addRow(new Object[]{
                    p.getId(),
                    p.getNo_identitas(),
                    p.getNama(),
                    p.getTgl_pembelian(),
                    p.getId_barang(),
                    p.getJumlah(),
                    p.getTot_harga(),
                    p.getDp(),
                    p.getStatus(),
                    p.getBonus(),});
            }
            crud.tutupKoneksi();
        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Mengambil Data");
        }
    }

    public void editData() {
        if (status.equals("add")) {
            txtId.setText("");
            txtNo_Identitas.setText("");
            txtNama.setText("");
            txtTgl_Pembelian.setText("");
            txtId_Barang.setText("");
            txtJumlah.setText("");
            txtTot_harga.setText("");
            txtDp.setText("");
            txtStatus.setText("");
            txtBonus.setText("");
        }
        txtId.setEditable(true);
        txtNo_Identitas.setEditable(true);
        txtNama.setEditable(true);
        txtTgl_Pembelian.setEditable(true);
        txtId_Barang.setEditable(true);
        txtJumlah.setEditable(true);
        txtTot_harga.setEditable(true);
        txtDp.setEditable(true);
        txtStatus.setEditable(true);
        txtBonus.setEditable(true);
        btSimpan.setEnabled(true);
        btBatal.setEnabled(true);
        btTambah.setEnabled(false);
        btEdit.setEnabled(false);
        btHapus.setEnabled(false);
        btBack.setEnabled(false);
        btExit.setEnabled(false);
        txtNo_Identitas.requestFocus();
    }

    private void kosongkanText() {
        txtId.setText("");
        txtNo_Identitas.setText("");
        txtNama.setText("");
        txtTgl_Pembelian.setText("");
        txtId_Barang.setText("");
        txtJumlah.setText("");
        txtTot_harga.setText("");
        txtDp.setText("");
        txtStatus.setText("");
        txtBonus.setText("");
    }

    private void readData() {
        txtId.setEditable(false);
        txtNo_Identitas.setEditable(false);
        txtNama.setEditable(false);
        txtTgl_Pembelian.setEditable(false);
        txtId_Barang.setEditable(false);
        txtJumlah.setEditable(false);
        txtTot_harga.setEditable(false);
        txtDp.setEditable(false);
        txtStatus.setEditable(false);
        txtBonus.setEditable(false);
        btSimpan.setEnabled(false);
        btBatal.setEnabled(false);
        btTambah.setEnabled(true);
        btEdit.setEnabled(true);
        btHapus.setEnabled(true);
        btBack.setEnabled(true);
        btExit.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btTambah = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btHapus = new javax.swing.JButton();
        btExit = new javax.swing.JButton();
        btBack = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbPembeli = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtNo_Identitas = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTgl_Pembelian = new javax.swing.JTextField();
        txtId_Barang = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        txtTot_harga = new javax.swing.JTextField();
        txtDp = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtBonus = new javax.swing.JTextField();
        btSimpan = new javax.swing.JButton();
        btBatal = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Trajan Pro", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Daftar Costumer PT.Tobrut");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(274, 274, 274))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        btTambah.setText("Tambah");
        btTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTambahActionPerformed(evt);
            }
        });

        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btHapus.setText("Hapus");
        btHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btHapusActionPerformed(evt);
            }
        });

        btExit.setText("Exit");
        btExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExitActionPerformed(evt);
            }
        });

        btBack.setText("Back");
        btBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btTambah)
                .addGap(18, 18, 18)
                .addComponent(btEdit)
                .addGap(18, 18, 18)
                .addComponent(btHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btBack)
                .addGap(18, 18, 18)
                .addComponent(btExit)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btTambah)
                    .addComponent(btEdit)
                    .addComponent(btHapus)
                    .addComponent(btExit)
                    .addComponent(btBack))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detail", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trajan Pro", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        tbPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPembeliMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbPembeli);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
        );

        jLabel3.setText("ID");

        jLabel2.setText("Nomor Identitas");

        jLabel4.setText("Nama");

        jLabel5.setText("Tanggal Pembelian");

        jLabel6.setText("ID Barang");

        jLabel7.setText("Bonus");

        jLabel8.setText("Status");

        jLabel9.setText("DP");

        jLabel10.setText("Total Harga");

        jLabel11.setText("Jumlah Barang");

        txtId.setEditable(false);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtNo_Identitas.setEditable(false);

        txtNama.setEditable(false);

        txtTgl_Pembelian.setEditable(false);

        txtId_Barang.setEditable(false);

        txtJumlah.setEditable(false);
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        txtTot_harga.setEditable(false);

        txtDp.setEditable(false);

        txtStatus.setEditable(false);
        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        txtBonus.setEditable(false);

        btSimpan.setText("Simpan");
        btSimpan.setEnabled(false);
        btSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSimpanActionPerformed(evt);
            }
        });

        btBatal.setText("Batal");
        btBatal.setEnabled(false);
        btBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(81, 81, 81)
                        .addComponent(txtNama))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTgl_Pembelian)
                            .addComponent(txtId_Barang)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(97, 97, 97)
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(31, 31, 31)
                        .addComponent(txtNo_Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 149, 149)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(txtDp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTot_harga, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBonus)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(btBatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel11)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSimpan))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10)
                    .addComponent(txtNo_Identitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTot_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(txtTgl_Pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(txtId_Barang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBonus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBatal))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void btSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSimpanActionPerformed
        Kendaraan k;
        if (status.equals("add")) {
            try {
                if (txtNo_Identitas.getText().isEmpty() || txtNama.getText().isEmpty()
                        || txtTgl_Pembelian.getText().isEmpty() || txtId_Barang.getText().isEmpty() || txtJumlah.getText().isEmpty() || txtTot_harga.getText().isEmpty()
                        || txtDp.getText().isEmpty() || txtStatus.getText().isEmpty() || txtBonus.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Data harus diisi semua");
                } else {
                    crud.bukaKoneksi();
                    p = new Pembeli();
                    p.setNo_identitas(txtNo_Identitas.getText());
                    p.setNama(txtNama.getText());
                    p.setTgl_pembelian(txtTgl_Pembelian.getText());
                    p.setId_barang(txtId_Barang.getText());
                    p.setJumlah(txtJumlah.getText());
                    p.setTot_harga(txtTot_harga.getText());
                    p.setDp(txtDp.getText());
                    p.setStatus(txtStatus.getText());
                    p.setBonus(txtBonus.getText());
                    crud.create(p);
                    getData();
                    readData();
                    crud.tutupKoneksi();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
        } else {
            try {
                if (txtNo_Identitas.getText().isEmpty() || txtNama.getText().isEmpty()
                        || txtTgl_Pembelian.getText().isEmpty() || txtId_Barang.getText().isEmpty() || txtJumlah.getText().isEmpty() || txtTot_harga.getText().isEmpty()
                        || txtDp.getText().isEmpty() || txtStatus.getText().isEmpty() || txtBonus.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Data harus diisi semua");
                } else {
                    crud.bukaKoneksi();
                    p = new Pembeli();
                    p.setId(Integer.parseInt(txtId.getText()));
                    p.setNo_identitas(txtNo_Identitas.getText());
                    p.setNama(txtNama.getText());
                    p.setTgl_pembelian(txtTgl_Pembelian.getText());
                    p.setId_barang(txtId_Barang.getText());
                    p.setJumlah(txtJumlah.getText());
                    p.setTot_harga(txtTot_harga.getText());
                    p.setDp(txtDp.getText());
                    p.setStatus(txtStatus.getText());
                    p.setBonus(txtBonus.getText());
                    crud.update(p);
                    getData();
                    readData();
                    crud.tutupKoneksi();
                    JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Data gagal disimpan");
            }
        }
    }                                        

    private void btNextActionPerformed(java.awt.event.ActionEvent evt) {                                       
        int tidakkeluar = JOptionPane.YES_NO_OPTION;
        int jadikeluar = JOptionPane.showConfirmDialog(null, "Ke halaman selanjutnya?", "Warning", tidakkeluar);
        if (jadikeluar == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new FormPembeli().setVisible(true);
        }
    }//GEN-LAST:event_btSimpanActionPerformed

    private void btTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTambahActionPerformed
        status = "add";
        this.editData();
    }//GEN-LAST:event_btTambahActionPerformed

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        status = "edit";
        if (txtId.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Data Masih Kosong, Silahkan Pilih Data");
        } else {
            this.editData();
        }
    }//GEN-LAST:event_btEditActionPerformed

    private void btBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBackActionPerformed
        int tidakkeluar = JOptionPane.YES_NO_OPTION;
        int jadikeluar = JOptionPane.showConfirmDialog(null, "Ke halaman selanjutnya?", "Warning", tidakkeluar);
        if (jadikeluar == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            new FormKendaraan().setVisible(true);
        }
    }//GEN-LAST:event_btBackActionPerformed

    private void btExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExitActionPerformed
        int tidakkeluar = JOptionPane.YES_NO_OPTION;
        int jadikeluar = JOptionPane.showConfirmDialog(null, "Keluar bro?", "Warning", tidakkeluar);
        if (jadikeluar == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btExitActionPerformed

    private void tbPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPembeliMouseClicked
        try {
            // TODO add your handling code here:
            int baris = tbPembeli.getSelectedRow();
            crud.bukaKoneksi();
            p = crud.readById(Integer.parseInt(tbPembeli.getValueAt(baris, 0).toString()));
            crud.tutupKoneksi();
            txtId.setText(Integer.toString(p.getId()));
            txtNo_Identitas.setText(p.getNo_identitas());
            

        } catch (SQLException | ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Ambil data gagal");
        }
    }//GEN-LAST:event_tbPembeliMouseClicked

    private void btBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBatalActionPerformed
        this.readData();
    }//GEN-LAST:event_btBatalActionPerformed

    private void btHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btHapusActionPerformed
    if (p == null) {
            JOptionPane.showMessageDialog(null, "Pilih Data Dahulu");
        } else {
            try {
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(null, "Hapus data?", "Warning", dialogButton);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    crud.bukaKoneksi();
                    crud.delete(p);
                    getData();
                    crud.tutupKoneksi();
                    p = null;
                    kosongkanText();
                }
            } catch (SQLException | ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "Hapus data gagal");
            }
        }
    }//GEN-LAST:event_btHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBack;
    private javax.swing.JButton btBatal;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExit;
    private javax.swing.JButton btHapus;
    private javax.swing.JButton btSimpan;
    private javax.swing.JButton btTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbPembeli;
    private javax.swing.JTextField txtBonus;
    private javax.swing.JTextField txtDp;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId_Barang;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo_Identitas;
    private javax.swing.JTextField txtStatus;
    private javax.swing.JTextField txtTgl_Pembelian;
    private javax.swing.JTextField txtTot_harga;
    // End of variables declaration//GEN-END:variables
}
